BOOTSTRAP_MPI = 40
SIZE_COEFFICIENT = 9.75 # coefficient to swap between coordinates in numbers of pixels and micrometers, #used in analysis stability
VOLUME_OFFSET = 1 #used in image_descriptors
PERIPHERAL_FRACTION_THRESHOLD = 10
NUM_CONTOURS = 100 # number of isolines for peripheral distance map
MAX_CELL_RADIUS = 300
DET_TOLERANCE = 0.00000001
PIXEL_PER_VOXEL = 16   # pixels per voxel width
VOXELS_PER_IMAGE = 512 # voxels per image width
RIPLEY_K_SIMULATION_NUMBER=20
IMAGE_WIDTH=512
IMAGE_HEIGHT=512
STRIPE_NUM=3
SLICE_THICKNESS=0.3
Z_LINE_SPACING=20
PIXELS_IN_SLICE= SLICE_THICKNESS * SIZE_COEFFICIENT
VOLUME_COEFFICIENT= ((1 / SIZE_COEFFICIENT)**2) * 0.3 # conversion from pixel volume to micrometer volume